const api = {  
   "retorno":{  
      "produtos":[  
            {  
            "produto":{  
               "codigo":"1",
               "tipo":"papelaria",
               "descricao":"Caneta azul",
               "unidade":"",
               "preco":"1.000",
               "precoCusto":"0.5000000",
               "pesoLiq":"1.000",
               "pesoBruto":"1.000",
               "estoqueMinimo":"0.00",
               "estoqueMaximo":null,
               "gtin":"",
               "gtinEmbalagem":"",
               "descricaoCurta":"Caneta",
               "descricaoComplementar":"Caneta azul BIC",
               "larguraProduto":"10",
               "alturaProduto":"89",
               "profundidadeProduto":"67",
               "unidadeMedida":"Centímetros",
               "dataInclusao":"2016-08-17",
               "dataAlteracao":"2016-08-17",
               "imageThumbnail":null,
               "nomeFornecedor":"Bling",
               "marca":"Marca de teste",
               "class_fiscal":"1234.56.78",
               "cest":"28.040.00",
               "origem":"1",
               "idGrupoProduto": "12345",
               "linkExterno": "https://minhaloja.com.br/cadeira-xyz-f5",
               "observacoes": "Observações da CADEIRA XYZ F5",
               "grupoProduto": "Móveis",
               "itensPorCaixa": 2,
               "volumes": 2,
               "urlVideo": "https://www.youtube.com/watch?v=zKKL-SgC5lY",
               "localizacao":"Prateleira B",
               "crossdocking": "2",
               "garantia": 4,
               "condicao": "Novo",
               "freteGratis": "S",
               "producao": "P",
               "dataValidade": "2019-11-20",
               "descricaoFornecedor": "Descrição do fornecedor",
               "imagem":[
                  {
                    "link": "",
                    "validade": "10/09/2017",
                    "tipoArmazenamento": "interno"
                  }],
                  
               }
            },
            {

               "produto":{  
                   "codigo":"2",
                   "tipo":"alimento",
                   "descricao":"Arroz",
                   "unidade":"",
                   "preco":"20.000",
                   "precoCusto":"0.5000000",
                   "pesoLiq":"1.000",
                   "pesoBruto":"1.000",
                   "estoqueMinimo":"0.00",
                   "estoqueMaximo":null,
                   "gtin":"",
                   "gtinEmbalagem":"",
                   "descricaoCurta":"Caneta",
                   "descricaoComplementar":"Caneta azul BIC",
                   "larguraProduto":"10",
                   "alturaProduto":"89",
                   "profundidadeProduto":"67",
                   "unidadeMedida":"Centímetros",
                   "dataInclusao":"2016-08-17",
                   "dataAlteracao":"2016-08-17",
                   "imageThumbnail":null,
                   "nomeFornecedor":"Bling",
                   "marca":"Marca de teste",
                   "class_fiscal":"1234.56.78",
                   "cest":"28.040.00",
                   "origem":"1",
                   "idGrupoProduto": "12345",
                   "linkExterno": "https://minhaloja.com.br/cadeira-xyz-f5",
                   "observacoes": "Observações da CADEIRA XYZ F5",
                   "grupoProduto": "Móveis",
                   "itensPorCaixa": 2,
                   "volumes": 20,
                   "urlVideo": "https://www.youtube.com/watch?v=zKKL-SgC5lY",
                   "localizacao":"Prateleira B",
                   "crossdocking": "2",
                   "garantia": 4,
                   "condicao": "Novo",
                   "freteGratis": "S",
                   "producao": "P",
                   "dataValidade": "2019-11-20",
                   "descricaoFornecedor": "Descrição do fornecedor",
                   "imagem":[
                       {
                       "link": "",
                       "validade": "10/09/2017",
                       "tipoArmazenamento": "interno"
                       }],
                   },
            },
            {

               "produto":{  
                  "codigo":"3",
                  "tipo":"móvel",
                  "descricao":"Armário",
                  "unidade":"",
                  "preco":"100.000",
                  "precoCusto":"0.5000000",
                  "pesoLiq":"1.000",
                  "pesoBruto":"1.000",
                  "estoqueMinimo":"0.00",
                  "estoqueMaximo":null,
                  "gtin":"",
                  "gtinEmbalagem":"",
                  "descricaoCurta":"Caneta",
                  "descricaoComplementar":"Caneta azul BIC",
                  "larguraProduto":"10",
                  "alturaProduto":"89",
                  "profundidadeProduto":"67",
                  "unidadeMedida":"Centímetros",
                  "dataInclusao":"2016-08-17",
                  "dataAlteracao":"2016-08-17",
                  "imageThumbnail":null,
                  "nomeFornecedor":"Bling",
                  "marca":"Marca de teste",
                  "class_fiscal":"1234.56.78",
                  "cest":"28.040.00",
                  "origem":"1",
                  "idGrupoProduto": "12345",
                  "linkExterno": "https://minhaloja.com.br/cadeira-xyz-f5",
                  "observacoes": "Observações da CADEIRA XYZ F5",
                  "grupoProduto": "Móveis",
                  "itensPorCaixa": 2,
                  "volumes": 20,
                  "urlVideo": "https://www.youtube.com/watch?v=zKKL-SgC5lY",
                  "localizacao":"Prateleira B",
                  "crossdocking": "2",
                  "garantia": 4,
                  "condicao": "Novo",
                  "freteGratis": "S",
                  "producao": "P",
                  "dataValidade": "2019-11-20",
                  "descricaoFornecedor": "Descrição do fornecedor",
                  "imagem":[
                     {
                       "link": "",
                       "validade": "10/09/2017",
                       "tipoArmazenamento": "interno"
                     }],
               }, 
            },
            {

               "produto":{  
                  "codigo":"4",
                  "tipo":"papelaria",
                  "descricao":"Lapis",
                  "unidade":"",
                  "preco":"1.000",
                  "precoCusto":"0.5000000",
                  "pesoLiq":"1.000",
                  "pesoBruto":"1.000",
                  "estoqueMinimo":"0.00",
                  "estoqueMaximo":null,
                  "gtin":"",
                  "gtinEmbalagem":"",
                  "descricaoCurta":"Caneta",
                  "descricaoComplementar":"Caneta azul BIC",
                  "larguraProduto":"10",
                  "alturaProduto":"89",
                  "profundidadeProduto":"67",
                  "unidadeMedida":"Centímetros",
                  "dataInclusao":"2016-08-17",
                  "dataAlteracao":"2016-08-17",
                  "imageThumbnail":null,
                  "nomeFornecedor":"Bling",
                  "marca":"Marca de teste",
                  "class_fiscal":"1234.56.78",
                  "cest":"28.040.00",
                  "origem":"1",
                  "idGrupoProduto": "12345",
                  "linkExterno": "https://minhaloja.com.br/cadeira-xyz-f5",
                  "observacoes": "Observações da CADEIRA XYZ F5",
                  "grupoProduto": "Móveis",
                  "itensPorCaixa": 2,
                  "volumes": 2,
                  "urlVideo": "https://www.youtube.com/watch?v=zKKL-SgC5lY",
                  "localizacao":"Prateleira B",
                  "crossdocking": "2",
                  "garantia": 4,
                  "condicao": "Novo",
                  "freteGratis": "S",
                  "producao": "P",
                  "dataValidade": "2019-11-20",
                  "descricaoFornecedor": "Descrição do fornecedor",
                  "imagem":[
                     {
                       "link": "",
                       "validade": "10/09/2017",
                       "tipoArmazenamento": "interno"
                     }],
               },
            }             
         
         //line
      ]

   }
}

export default api;